// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPRNr2AMxfhu0BXDYqzQRY5wgUVcQCrRA',
    appId: '1:500540516941:web:63c438db465dd36dfa0a04',
    messagingSenderId: '500540516941',
    projectId: 'flutterfiredemo-b52bc',
    authDomain: 'flutterfiredemo-b52bc.firebaseapp.com',
    storageBucket: 'flutterfiredemo-b52bc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv0qt2WV7sRUBU7VRHYAiG9vXpk5MvJBI',
    appId: '1:500540516941:android:df7af7a35e18a1d3fa0a04',
    messagingSenderId: '500540516941',
    projectId: 'flutterfiredemo-b52bc',
    storageBucket: 'flutterfiredemo-b52bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9e7WuSedvKVoxt7Vs70qfPv-Sorg49Mg',
    appId: '1:500540516941:ios:d7ff5ce07dec4048fa0a04',
    messagingSenderId: '500540516941',
    projectId: 'flutterfiredemo-b52bc',
    storageBucket: 'flutterfiredemo-b52bc.appspot.com',
    iosClientId: '500540516941-6k21kml3fnchdfgji9sf434f9ehjo2dh.apps.googleusercontent.com',
    iosBundleId: 'com.workshop.flutterfirebase.flutterfire',
  );
}
